// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RailBooking.Api.Data;

#nullable disable

namespace RailBooking.Api.Data.Migrations
{
    [DbContext(typeof(RailBookingDbContext))]
    [Migration("20260803113942_IncreaseReservedCoachSeatCount")]
    partial class IncreaseReservedCoachSeatCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RailBooking.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DestinationSequence")
                        .HasColumnType("integer");

                    b.Property<int>("DestinationStationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FareAmount")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("OriginSequence")
                        .HasColumnType("integer");

                    b.Property<int>("OriginStationId")
                        .HasColumnType("integer");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SeatId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TripDepartureId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinationStationId");

                    b.HasIndex("OriginStationId");

                    b.HasIndex("TripDepartureId");

                    b.HasIndex("SeatId", "TripDepartureId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RailBooking.Domain.Entities.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeatCount")
                        .HasColumnType("integer");

                    b.Property<int>("TrainId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("TrainId", "CoachNumber")
                        .IsUnique();

                    b.ToTable("Coaches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoachNumber = 1,
                            SeatCount = 20,
                            TrainId = 1,
                            Type = "Reserved"
                        },
                        new
                        {
                            Id = 2,
                            CoachNumber = 2,
                            SeatCount = 20,
                            TrainId = 1,
                            Type = "Reserved"
                        },
                        new
                        {
                            Id = 3,
                            CoachNumber = 3,
                            SeatCount = 20,
                            TrainId = 1,
                            Type = "Reserved"
                        },
                        new
                        {
                            Id = 4,
                            CoachNumber = 4,
                            SeatCount = 80,
                            TrainId = 1,
                            Type = "Unreserved"
                        },
                        new
                        {
                            Id = 5,
                            CoachNumber = 5,
                            SeatCount = 80,
                            TrainId = 1,
                            Type = "Unreserved"
                        },
                        new
                        {
                            Id = 6,
                            CoachNumber = 6,
                            SeatCount = 80,
                            TrainId = 1,
                            Type = "Unreserved"
                        },
                        new
                        {
                            Id = 7,
                            CoachNumber = 7,
                            SeatCount = 80,
                            TrainId = 1,
                            Type = "Unreserved"
                        },
                        new
                        {
                            Id = 8,
                            CoachNumber = 8,
                            SeatCount = 80,
                            TrainId = 1,
                            Type = "Unreserved"
                        });
                });

            modelBuilder.Entity("RailBooking.Domain.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("integer");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoachId", "SeatNumber")
                        .IsUnique();

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoachId = 1,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            CoachId = 1,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            CoachId = 1,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            CoachId = 1,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            CoachId = 1,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            CoachId = 1,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 7,
                            CoachId = 1,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 8,
                            CoachId = 1,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 9,
                            CoachId = 1,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 10,
                            CoachId = 1,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 11,
                            CoachId = 1,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 12,
                            CoachId = 1,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 13,
                            CoachId = 1,
                            SeatNumber = 13
                        },
                        new
                        {
                            Id = 14,
                            CoachId = 1,
                            SeatNumber = 14
                        },
                        new
                        {
                            Id = 15,
                            CoachId = 1,
                            SeatNumber = 15
                        },
                        new
                        {
                            Id = 16,
                            CoachId = 1,
                            SeatNumber = 16
                        },
                        new
                        {
                            Id = 17,
                            CoachId = 1,
                            SeatNumber = 17
                        },
                        new
                        {
                            Id = 18,
                            CoachId = 1,
                            SeatNumber = 18
                        },
                        new
                        {
                            Id = 19,
                            CoachId = 1,
                            SeatNumber = 19
                        },
                        new
                        {
                            Id = 20,
                            CoachId = 1,
                            SeatNumber = 20
                        },
                        new
                        {
                            Id = 21,
                            CoachId = 2,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 22,
                            CoachId = 2,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 23,
                            CoachId = 2,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 24,
                            CoachId = 2,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 25,
                            CoachId = 2,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 26,
                            CoachId = 2,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 27,
                            CoachId = 2,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 28,
                            CoachId = 2,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 29,
                            CoachId = 2,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 30,
                            CoachId = 2,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 31,
                            CoachId = 2,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 32,
                            CoachId = 2,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 33,
                            CoachId = 2,
                            SeatNumber = 13
                        },
                        new
                        {
                            Id = 34,
                            CoachId = 2,
                            SeatNumber = 14
                        },
                        new
                        {
                            Id = 35,
                            CoachId = 2,
                            SeatNumber = 15
                        },
                        new
                        {
                            Id = 36,
                            CoachId = 2,
                            SeatNumber = 16
                        },
                        new
                        {
                            Id = 37,
                            CoachId = 2,
                            SeatNumber = 17
                        },
                        new
                        {
                            Id = 38,
                            CoachId = 2,
                            SeatNumber = 18
                        },
                        new
                        {
                            Id = 39,
                            CoachId = 2,
                            SeatNumber = 19
                        },
                        new
                        {
                            Id = 40,
                            CoachId = 2,
                            SeatNumber = 20
                        },
                        new
                        {
                            Id = 41,
                            CoachId = 3,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 42,
                            CoachId = 3,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 43,
                            CoachId = 3,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 44,
                            CoachId = 3,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 45,
                            CoachId = 3,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 46,
                            CoachId = 3,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 47,
                            CoachId = 3,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 48,
                            CoachId = 3,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 49,
                            CoachId = 3,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 50,
                            CoachId = 3,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 51,
                            CoachId = 3,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 52,
                            CoachId = 3,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 53,
                            CoachId = 3,
                            SeatNumber = 13
                        },
                        new
                        {
                            Id = 54,
                            CoachId = 3,
                            SeatNumber = 14
                        },
                        new
                        {
                            Id = 55,
                            CoachId = 3,
                            SeatNumber = 15
                        },
                        new
                        {
                            Id = 56,
                            CoachId = 3,
                            SeatNumber = 16
                        },
                        new
                        {
                            Id = 57,
                            CoachId = 3,
                            SeatNumber = 17
                        },
                        new
                        {
                            Id = 58,
                            CoachId = 3,
                            SeatNumber = 18
                        },
                        new
                        {
                            Id = 59,
                            CoachId = 3,
                            SeatNumber = 19
                        },
                        new
                        {
                            Id = 60,
                            CoachId = 3,
                            SeatNumber = 20
                        });
                });

            modelBuilder.Entity("RailBooking.Domain.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SequenceNumber")
                        .IsUnique();

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistanceKm = 0m,
                            Name = "Colombo Fort",
                            SequenceNumber = 0
                        },
                        new
                        {
                            Id = 2,
                            DistanceKm = 66m,
                            Name = "Rambukkana",
                            SequenceNumber = 1
                        },
                        new
                        {
                            Id = 3,
                            DistanceKm = 121m,
                            Name = "Kandy",
                            SequenceNumber = 2
                        },
                        new
                        {
                            Id = 4,
                            DistanceKm = 127m,
                            Name = "Peradeniya",
                            SequenceNumber = 3
                        },
                        new
                        {
                            Id = 5,
                            DistanceKm = 168m,
                            Name = "Hatton",
                            SequenceNumber = 4
                        },
                        new
                        {
                            Id = 6,
                            DistanceKm = 186m,
                            Name = "Nanu Oya",
                            SequenceNumber = 5
                        },
                        new
                        {
                            Id = 7,
                            DistanceKm = 194m,
                            Name = "Haputale",
                            SequenceNumber = 6
                        },
                        new
                        {
                            Id = 8,
                            DistanceKm = 204m,
                            Name = "Bandarawela",
                            SequenceNumber = 7
                        },
                        new
                        {
                            Id = 9,
                            DistanceKm = 216m,
                            Name = "Ella",
                            SequenceNumber = 8
                        },
                        new
                        {
                            Id = 10,
                            DistanceKm = 230m,
                            Name = "Badulla",
                            SequenceNumber = 9
                        });
                });

            modelBuilder.Entity("RailBooking.Domain.Entities.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Podi Menike"
                        });
                });

            modelBuilder.Entity("RailBooking.Domain.Entities.TripDeparture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<int>("TrainId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainId", "ServiceDate")
                        .IsUnique();

                    b.ToTable("TripDepartures");
                });

            modelBuilder.Entity("RailBooking.Domain.Entities.Booking", b =>
                {
                    b.HasOne("RailBooking.Domain.Entities.Station", null)
                        .WithMany()
                        .HasForeignKey("DestinationStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RailBooking.Domain.Entities.Station", null)
                        .WithMany()
                        .HasForeignKey("OriginStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RailBooking.Domain.Entities.Seat", null)
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RailBooking.Domain.Entities.TripDeparture", null)
                        .WithMany()
                        .HasForeignKey("TripDepartureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RailBooking.Domain.Entities.Coach", b =>
                {
                    b.HasOne("RailBooking.Domain.Entities.Train", null)
                        .WithMany("Coaches")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RailBooking.Domain.Entities.Seat", b =>
                {
                    b.HasOne("RailBooking.Domain.Entities.Coach", null)
                        .WithMany("Seats")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RailBooking.Domain.Entities.TripDeparture", b =>
                {
                    b.HasOne("RailBooking.Domain.Entities.Train", null)
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RailBooking.Domain.Entities.Coach", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("RailBooking.Domain.Entities.Train", b =>
                {
                    b.Navigation("Coaches");
                });
#pragma warning restore 612, 618
        }
    }
}
